### PR TITLE
Work for Github Issue 65.

### PR DESCRIPTION
**Pull request by lafent**
Relocates the tests to the exercises directory and updates the Makefile to ignore the new directory.  

https://github.com/exercism/xphp/issues/65

### CODE REVIEW

**Comment by kytrinyx** [comment]
Excellent, thanks! Would you mind squashing the commits, please? The commit should explain what the commit does, and reference the GitHub issue by number in order to close the correct issue automatically.

```
Move exercises to subdirectory. Closes #65
```

See http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html for a great explanation of what makes a good commit message (notice "Move", not "Moved" or "Moves").

See https://help.github.com/articles/closing-issues-via-commit-messages/ for an explanation about closing issues automatically from a commit message.

**Comment by lafent** [comment]
I think I might have done the right thing.  I've never had to rebase before, so if it's not right, please let me know.

**Comment by kytrinyx** [comment]
If you look at the list of the commits you'll see two things that show that this hasn't been rebased and squashed: First, look for the "merge" commits. These happen when the history diverges in the two branches (rebasing would put one history after the other, so there wouldn't be a merge). The second is that there are 4 commits. When you've successfully squashed then there will only be one commit.

Here's a blog post about how to squash: http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request

Since you're working on master, though, instead of a branch, you will need to do things slightly differently.

What do you get when you type `git remote -v`?

**Comment by lafent** [comment]
I may have mangled this unintentionally.  

When I run the `git remote -v` (on both my master or the branch I merged
into my master):

origin  https://github.com/lafent/xphp (fetch)
origin  https://github.com/lafent/xphp (push)

From my forked copy of xphp I did a `git checkout -b exercises-relocation`, 
did the move, committed things, then figured out that Travis was having
issues, when back, fixed the Travis hiccup.  

Since the scope of work is so small, I can nuke it, and redo the commit
in a single go.  I'm not sure if that's less hassle or what.  I just
don't know what Github would do with the pull request or if it can be
killed in some fashion.

Sorry for the headache.

L

**Comment by lafent** [comment]
Maybe this is right now?

**Comment by kytrinyx** [comment]
It looks like you need to add this repository as a remote:

```
git remote add upstream https://github.com/exercism/xphp.git
```

That said, it does look right now. Thanks!

**Pull request merged**
