### PR TITLE
Add markdown parser exercise

### PR DESCRIPTION
**Pull request by petemcfarlane**
As talked about here: https://github.com/exercism/x-common/pull/262

### CODE REVIEW

**Comment by petemcfarlane** [comment]
Hi @brettsantore, would you have time to have a look/go at the above exercise? It's a bit different to usual in that it provides an already passing solution, but a pretty ugly one. The exercise is in refactoring the existing code, whilst keeping the tests passing. 
Some more background here exercism/x-common#262
Any feedback would be appreciated 😄

**Comment by brettsantore** [comment]
What specifically do you want to look at?

**Comment by petemcfarlane** [comment]
I wondered firstly if it made sense and worked. Secondly, if you had any opinions or suggestions to improve the exercise? Obviously without refactoring it completely to some good code, that would defeat the point.

**Comment by brettsantore** [comment]
How do I get this locally? This is my first time working on git with a team

**Comment by petemcfarlane** [comment]
Ah ok, I'll try and walk you through the steps.
Have you cloned the `exercism/xphp` repository or is it your own local fork? An easy way to tell is from your command line if you execute `git remote -v` it should show you the remote repositories (you can have more than one)
```
> git remote -v
upstream	git@github.com:exercism/xphp.git (fetch)
upstream	git@github.com:exercism/xphp.git (push)
origin	git@github.com:petemcfarlane/xphp.git (fetch)
origin	git@github.com:petemcfarlane/xphp.git (push)
```

If you don't see the `exercism/xphp` branch set up you can add it with `git remote add upstream git@github.com:exercism/xphp.git` (It doesn't matter if you call it upstream, origin or anything else, but upstream is commonly used here, if you already have origin pointing to your forked repo).

Now fetch the details of the remote branches with `git fetch upstream`. 

To check, if you exec `git branch -r` you should see the remote branches on origin and upstream. You can directly check one of these out with `git checkout add-markdown`.

Let me know how you get on or if anything doesn't make sense! Thanks for trying.

**Comment by brettsantore** [comment]
So you want me to clean up the example some?

**Comment by petemcfarlane** [comment]
I'm not sure weather we should have a cleaner example or just leave it as it's passing the tests. I'm more interested in the process: does the exercise make sense, can you see how one might refactor parts, are there any unclear parts or mistakes, do the tests make sense, any spelling mistakes etc.
If you have any critiques you can comment directly on a line in GitHub by looking at the [Files Changed](https://github.com/exercism/xphp/pull/87/files) at the top of this page and I'll try to fix them. If you think it looks ok as it is then I can merge this PR.

**Comment by brettsantore** [comment]
A couple thoughts and I'll dig around. I think the example should have some kind of refactoring, since it does represent an a way to solve the exercise. Although, this is unique since the code already passes.

I'm not sure I see a goal, other than refactoring. Is there a way to add a goal or back story, similar to the Gilded Rose Kata?

**Pull request merged**
