### PR TITLE
Fix issue 70, improve clock tests.

### PR DESCRIPTION
**Pull request by petemcfarlane**

### CODE REVIEW

**Comment by kytrinyx** [comment]
Thanks, Pete. I can't remember the deal in the PHP track. Did we decide to remove the skips from the exercises?

**Comment by petemcfarlane** [comment]
Nope, that’s my fault! I couldn’t get the makefile working so I was running the tests from the cli instead. I’ll correct that now!

**Comment by kytrinyx** [comment]
Ah, let me see if I can figure out what's going on with the makefile.

**Comment by kytrinyx** [comment]
Oh. Uh--the make file isn't actually running any tests at all on CI. I just fixed the same thing on the Ruby track this morning. Oops.

**Comment by petemcfarlane** [comment]
Ahh good spot! I've fixed that in the last commit 976261d :+1:

**Comment by kytrinyx** [comment]
That travis run looks *much* better.

Would you mind sticking the makefile fix into a different PR? If you're on you way to work or something I can cherrypick it locally.

**Comment by petemcfarlane** [comment]
Yup, I've moved it into PR #72

**Comment by kytrinyx** [comment]
Sweet, thanks so much!

**Pull request merged**
