### PR TITLE
Anagram: Tests and Example

### PR DESCRIPTION
**Pull request by ecrmnn**
This PR adds tests and example for the Anagram exercise.

Tests taken from [x-common/anagram.json](https://github.com/exercism/x-common/blob/master/anagram.json)

### CODE REVIEW

**Comment by petemcfarlane** [comment]
Just my opinion again, but I don't think the anagram detector really needs to be an object 😁 
I think `detectAnagrams('master', ['stream', 'pigeon', 'maters'])` would be much cleaner. In other tracks, including [Python](https://github.com/exercism/xpython/blob/4e4f1e5b65617f6ad419d2df5a730a43ebd59eeb/exercises/anagram/anagram_test.py), they use a function but in others such as [JavaScript](https://github.com/exercism/xjavascript/blob/9cfb49cd21aba663da308e72580064e95ac941dd/exercises/anagram/anagram.spec.js) an object is used so there seems to be some split ideas.

Theres a couple of tests that I'm not sure are needed
 - `testDetectsUnicodeAnagrams` and `testEliminatesMisleadingUnicodeAnagrams` - do we need this extra level of complexity?
 - `testAnagramsMustUseAllLettersExactlyOnce2` - this seems very similar to a previous test and I think is redundant.
 - `testAcceptsStringArguments` and `testAcceptsSingleStringArgument` - Personally I think using `func_get_args()` and determining if you're given a string, array or multiple arguments is not a very nice thing to do. It adds a new level of confusion and can introduce all kinds of bugs in production code, we shouldn't be encouraging people to use this! I would suggest only accepting an `array` of candidate words instead.

**Comment by ecrmnn** [comment]
As mentioned in OP, tests are identical from ``anagram.json``. Thought it was preferable to have identical tests across all language tracks, but if you think they are redundant I'll remove them.

I don't like ``func_get_args()`` at all, just added it so you could pass unlimited strings like the JS implementation. I'll remove it and only accept an array

**Comment by petemcfarlane** [comment]
You're right about the `patter/tapper` test, I'm sorry. I think in this case it would be best to leave it in for consistency (but I still think it's redundant in the master anagram.json file too really 😉)

**Comment by ecrmnn** [comment]
Refactored

**Comment by kytrinyx** [comment]
>  I still think it's redundant in the master anagram.json file too really

Yeah, probably. I've opened an issue on the metadata repo about it.

**Comment by ecrmnn** [comment]
@kytrinyx Want me to remove the patter/tapper tests?

**Comment by kytrinyx** [comment]
I haven't heard back from the other maintainers on this (in the above linked issue). Let's leave it as is for now.

**Pull request merged**
