### PR TITLE
Implement the pascals triangle, nth-prime & binary search exercises

### PR DESCRIPTION
**Pull request by arthurchipdean**

### CODE REVIEW

**Comment by petemcfarlane** [comment]
Hi @arthurchipdean, looks like you only needed that last commit e58e7cc, in this pull request? Could you update your master branch with the exercism master branch, that should clean up this PR. Some notes found here: https://help.github.com/articles/syncing-a-fork/ Let me know if you need any help.

Thanks!

**Comment by arthurchipdean** [comment]
I'm doing a `git pull` and `git push` and it's saying everything is up to date. I'm on the master branch.

**Comment by arthurchipdean** [comment]
It's odd. Those other two commits should already be in master. They were merged yesterday. I'm not sure why it's saying there are three. Any ideas? Thanks

**Comment by petemcfarlane** [comment]
I think you haven't synced with the upstream, your forked origin master is probably out of date with the original repo. 
To do this in a terminal go to the project directory

git fetch upstream
git checkout master
git merge upstream/master
git push

Hope that helps!

**Comment by arthurchipdean** [comment]
@petemcfarlane Is there anything else I need to do for this PR? Thank you!

**Comment by petemcfarlane** [comment]
Sorry to keep you waiting @arthurchipdean. It looks ok now, thanks! Please would you mind making each exercise it's own PR in the future? It just makes it a bit easier to manage if there is one exercise per PR, to provide feedback, or not hold up the other work from being merged if there is an issue with one exercise.

**Comment by arthurchipdean** [comment]
@petemcfarlane  my plan was to create multiple PRs but github automatically added all my commits to this PR.

**Pull request merged**
