### PR TITLE
WordCount: Tests and Example

### PR DESCRIPTION
**Pull request by ecrmnn**
This PR adds tests and example for the WordCount exercise.

Tests taken from [x-common/word-count.json](https://github.com/exercism/x-common/blob/master/word-count.json) and additional tests from JavaScript implementation

### CODE REVIEW

**Comment by petemcfarlane** [comment]
Thanks for the PR 👍 I just have a couple of suggestions before merging:
 - If it makes sense for the exercise, we prefer to use functions rather than classes (as per issue #29) so the tests might instead look like `$this->assertEquals(['word' => 1], wordCount('word'));`. This makes sense in this exercise because there is no state to preserve.
 - I would probably not include the `testCountsInternationalCharacters` test, this seems to be conflicting with testing it ignores punctuation, and many of the other language tracks don't include this. I noticed it is in [the javascript version](https://github.com/exercism/xjavascript/blob/9cfb49cd21aba663da308e72580064e95ac941dd/exercises/word-count/word-count.spec.js#L21) but they also test that the returned array __includes__ punctuation, unlike some of the other language tracks.

The rest looks good!

**Comment by ecrmnn** [comment]
I can see how just using a function would make it "easier", but don't you feel a class is more "real world"?
In an "actual project" I wouldn't have a global function called ``wordCount()``, but rather a class.

Also noticed ``Bowling``, ``Clock``, ``Connect``, ``DifferenceOfSquares`` and ``RobotName`` are all classes.

What's your opinion on this?

I agree with you on removing ``testCountsInternationalCharacters``. Just wanted some feedback on it. It adds too much complexity.

**Comment by petemcfarlane** [comment]
I did used to have the same view as you, thinking that using objects would be closer to my day-to-day OO work, but then I became a functional programmer ;-) 

But my serious **_opinion_** is that a function is cleaner to test, less code to write and easier to understand for the person practicing the exercise, and what we're testing in this exercise is how to group/count words, not how to do OOP!

Bowling, Clock and a few others are written in an OO style because they all have __state__. Objects are great for encapsulating state with behaviour or functionality. But in many of these exercises, there is no state, only functionality. In those situations functions are much cleaner and simpler.

**Comment by ecrmnn** [comment]
Refactored to function and removed ``international characters``-test

**Comment by ecrmnn** [comment]
@kytrinyx Ready for merge?

**Comment by petemcfarlane** [comment]
Thanks @ecrmnn, I've now merged it!

**Pull request merged**
