### PR TITLE
Implements the space-age exercise

### PR DESCRIPTION
**Pull request by camilopayan**

### CODE REVIEW

**Comment by kytrinyx** [comment]
@petemcfarlane Will you have a moment to review this before the end of October (tomorrow)? I want to make sure that @camilopayan qualifies for the Hacktoberfest t-shirt. If not, just let me know and I'll give it a rough review, merge it, and then we can have a second round of tweaks in a new PR.

**Comment by camilopayan** [comment]
Cool, I removed the earth tests. You're right, it didn't really add anything.

**Comment by camilopayan** [comment]
I had also forgotten the test skipping 😓

**Comment by petemcfarlane** [comment]
Thanks!

**Pull request merged**
