### PR TITLE
Adding the allergies exercices

### PR DESCRIPTION
**Pull request by mikeSimonson**

### CODE REVIEW

**Comment by camilopayan** [comment]
Just need to fix the conflict on the config.json file. That's a rebase away.

**Comment by kytrinyx** [comment]
I'll go ahead and fix it so that we can get this in before the end of #hacktoberfest

**Comment by kytrinyx** [comment]
Merged in 05c5a404a0ee4d117f7050fde8478d23a53e55b7

Thank you :heart:

**Comment by mikeSimonson** [comment]
@kytrinyx Thanks I missed the rebase message.

**Pull request closed without merging**
